### PR TITLE
Gradle cleanup, Temp fix crash, Mixin cleanup

### PR DESCRIPTION
**Pull request by Edrow-6**
Hi,
I temporarily fixed the crash, improved the "shouldApplyMixin" condition and cleaned up the gradle file to make it more organized.

### CODE REVIEW

**Comment by Edrow-6** [comment]
I got a little confused with the commits on my side because I'm not used to creating braches and making pull requests :p

**Comment by Globox1997** [comment]
Honestly not that happy with this PR
Lots of format changes and the main issue not solved
The main issue is, in prod env the game crashes when the player tries to open the level screen while inventorio isn't loaded cause for some reason it uses the imports even if they can't be reached by code

**Comment by Edrow-6** [comment]
Idk how to solve this, I'm new in java :(

**Comment by Globox1997** [comment]
do you have discord? Globox_Z #1024

**Comment by Globox1997** [comment]
Not necessary anymore I think

**Pull request closed without merging**
