### PR TITLE
Inventorio Compatibility, Toggle Inv Button

### PR DESCRIPTION
**Pull request by Edrow-6**
**Update 1.3.2**

Added Inventorio Compatibility _(with button fallback corresponding to inventory type "default" and "inventorio")_
image

Added a config to toggle inventory button _(toggle in both gui)_
image

Added missing comment in config file
image

Fix typo and update Readme

### CODE REVIEW

**Comment by Globox1997** [comment]
hey Edrow-6, this looks pretty good even tho the mod Inventorio looks pretty odd in my opinion.
Not sure why you are using assertions, feels kinda weird but except of the Inventorio mentioning at the readme it is dope.

**Comment by Globox1997** [comment]
I feel like if inventorio compat is mentioned, other compatibilities should be mentioned too but since I don't do that, I'm against it

**Comment by Edrow-6** [comment]
Hi, i use assertions because this.client and this.client.player may produce "NullPointerException".
ex: image

**Comment by Edrow-6** [comment]
I removed the mention in the readme :D

**Comment by Globox1997** [comment]
Thanks :) Never saw assertions to be honest^^

**Comment by Globox1997** [comment]
Houston Houston we got a problem.
If inventorio isn't loaded outside of dev env, the game will crash due to a class not found error:
`java.lang.NoClassDefFoundError: me/lizardofoz/inventorio/client/ui/InventorioScreen`
[https://github.com/Globox1997/LevelZ/blob/1.18/src/main/java/net/levelz/gui/LevelzScreen.java#L84](https://github.com/Globox1997/LevelZ/blob/1.18/src/main/java/net/levelz/gui/LevelzScreen.java#L84)

**Pull request merged**
