### PR TITLE
fix NPE possibility in onUserDamagedMixin and onTargetDamagedMixin

### PR DESCRIPTION
**Pull request by urmet**
fix for #115

### CODE REVIEW

**Comment by Globox1997** [comment]
hey urmet, I don't think this is a good solution for the issue cause it will break other cases then those I try to cancel.

**Comment by Globox1997** [comment]
Fixed it with [https://github.com/Globox1997/LevelZ/commit/9e7ca1cddffbf9a963a94191db0dd5b9fe7d2aa2](https://github.com/Globox1997/LevelZ/commit/9e7ca1cddffbf9a963a94191db0dd5b9fe7d2aa2)

**Comment by urmet** [comment]
code flow wise you commited the exact same change. I just avoided adding another nesting level and instead removed one to improve readability while not changing any of the code logic :)

**Comment by Vaelzan** [comment]
> hey urmet, I don't think this is a good solution for the issue cause it will break other cases then those I try to cancel.

I'm curious as to what you think it would break, as this appears to just be a cleaner, more maintainable version of the fix that you committed, and otherwise equivalent. Am I missing something?

(for context as to the question, it's generally a good practice to use the Return Early Pattern where suitable, such as in this case - https://medium.com/swlh/return-early-pattern-3d18a41bba8)

**Pull request closed without merging**
