### PR TITLE
Add crafting example datapack

### PR DESCRIPTION
**Pull request by JLHasson**
Add crafting example based on README.md into the example datapack

### CODE REVIEW

**Comment by Globox1997** [comment]
Hey do you have discord?
Globox_Z #1024

**Comment by JLHasson** [comment]
Sure, I’m HansonSP#8282 in your server

**Comment by Globox1997** [comment]
Pls set the required lvl to 0
The example datapack has only 0d requirements

**Comment by JLHasson** [comment]
Done 💯

**Comment by Globox1997** [comment]
Gonna pull it but you forgot the file names^^

**Pull request merged**
